name: Build CPUthermal


on:

  push:

    branches:

      - main

    tags:

      - "v*"


  workflow_dispatch:




jobs:


  build:


    name: Build ${{ matrix.scheme }}


    runs-on: macos-latest



    strategy:

      fail-fast: false

      matrix:

        scheme:

          - rootless

          - roothide




    steps:



    # -----------------------------
    # 下载源码
    # -----------------------------

    - name: Checkout

      uses: actions/checkout@v4





    # -----------------------------
    # 安装依赖
    # -----------------------------

    - name: Install dependencies

      run: |

        brew update

        brew install ldid



    # -----------------------------
    # 安装 Theos
    # -----------------------------

    - name: Install Theos

      run: |


        git clone --recursive \
        https://github.com/theos/theos.git \
        $HOME/theos


        echo "THEOS=$HOME/theos" >> $GITHUB_ENV


        echo "$HOME/theos/bin" >> $GITHUB_PATH





    # -----------------------------
    # 安装 SDK
    # -----------------------------

    - name: Install iOS SDK


      run: |


        mkdir -p $HOME/theos/sdks


        cd $HOME/theos/sdks



        if [ ! -d "iPhoneOS16.5.sdk" ]; then


          git clone \
          https://github.com/theos/sdks.git \
          temp-sdk



          cp -R temp-sdk/*.sdk .


          rm -rf temp-sdk


        fi



        ls -la $HOME/theos/sdks






    # -----------------------------
    # 修改 SDK 版本
    # -----------------------------

    - name: Fix SDK target


      run: |


        sed -i '' \
        's/iphone:clang:16.5:15.0/iphone:clang:latest:15.0/g' \
        Makefile || true






    # -----------------------------
    # 编译
    # -----------------------------

    - name: Build package


      run: |


        export THEOS=$HOME/theos



        make clean



        if [ "${{ matrix.scheme }}" = "rootless" ]

        then


          echo "Building rootless"



          make package \
          FINALPACKAGE=1 \
          THEOS_PACKAGE_SCHEME=rootless



        else


          echo "Building roothide"



          make package \
          FINALPACKAGE=1 \
          THEOS_PACKAGE_SCHEME=roothide



        fi





    # -----------------------------
    # 保存 deb
    # -----------------------------

    - name: Collect deb


      run: |


        mkdir output


        cp packages/*.deb output/



        for file in output/*.deb

        do


          mv "$file" \
          "output/CPUthermal-${{ matrix.scheme }}.deb"



        done






    # -----------------------------
    # 上传 Artifact
    # -----------------------------

    - name: Upload package


      uses: actions/upload-artifact@v4


      with:


        name: CPUthermal-${{ matrix.scheme }}


        path: output/*.deb








# =====================================================
# GitHub Release
# =====================================================


  release:


    needs: build


    if: startsWith(github.ref,'refs/tags/')


    runs-on: ubuntu-latest



    steps:


    - name: Download packages


      uses: actions/download-artifact@v4


      with:


        path: release





    - name: Create Release


      uses: softprops/action-gh-release@v2


      with:


        files:

          release/**/*.deb



      env:


        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}